import React, { useState, useEffect } from 'react';
import heroLightAsset from '../assets/Hero Page.png';
import heroDarkAsset from '../assets/hero-dark.jpg';

const TermsPage = ({ setActiveTab, isDarkMode: isDarkModeProp }) => {
  const [scrollProgress, setScrollProgress] = useState(0);
  const [showBackToTop, setShowBackToTop] = useState(false);
  const [isDark, setIsDark] = useState(() => 
    isDarkModeProp !== undefined ? isDarkModeProp : (typeof document !== 'undefined' && document.documentElement.classList.contains('dark'))
  );

  useEffect(() => {
    const handleScroll = () => {
      const totalHeight = document.documentElement.scrollHeight - window.innerHeight;
      if (totalHeight > 0) {
        const currentProgress = (window.scrollY / totalHeight) * 100;
        setScrollProgress(currentProgress);
      }
      setShowBackToTop(window.scrollY > 400);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const checkDark = () => {
      if (typeof document !== 'undefined') {
        setIsDark(document.documentElement.classList.contains('dark'));
      }
    };
    checkDark();
    const observer = new MutationObserver(checkDark);
    if (typeof document !== 'undefined') {
      observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    }
    return () => observer.disconnect();
  }, []);

  const activeDarkMode = isDarkModeProp !== undefined ? isDarkModeProp : isDark;

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const termsSections = [
    {
      id: "acceptance",
      num: "01",
      icon: "task_alt",
      title: "Acceptance of Terms",
      content: "By accessing, browsing, or utilizing TASK's website, agency services, digital assets, or consultation proposals, you (\"Client\", \"User\", or \"Visitor\") acknowledge that you have read, understood, and agreed to be legally bound by these Terms & Conditions. If you do not agree to these terms in their entirety, you must immediately cease using our website and digital services."
    },
    {
      id: "services",
      num: "02",
      icon: "design_services",
      title: "Agency Services",
      content: "TASK provides bespoke digital architecture and agency solutions including, but not limited to:",
      bullets: [
        "Website Design & Interactive UI/UX Architecture",
        "Full-Stack Web Application Development & API Integration",
        "Brand Identity, Logo Design & Visual System Standards",
        "Ongoing Website Maintenance, Security & Cloud Monitoring",
        "E-Commerce Solutions & High-Conversion Landing Page Optimization"
      ],
      note: "All project deliverables are developed according to the explicit Scope of Work (SOW) agreed upon in writing prior to project kickoff."
    },
    {
      id: "quotes-pricing",
      num: "03",
      icon: "request_quote",
      title: "Quotes & Pricing Structure",
      content: "Custom agency proposals, cost estimates, and digital quotes generated by TASK remain valid for 30 calendar days from issuance. Prices quoted are based on the initial project scope requested by the Client. Any additional features, scope expansions, or design alterations requested after agreement approval will be evaluated as separate change orders with confirmed pricing before work commences."
    },
    {
      id: "payments",
      num: "04",
      icon: "payments",
      title: "Payment Terms & Schedules",
      content: "To maintain project momentum and reserve dedicated agency resources:",
      bullets: [
        "Advance Initial Deposit: A non-refundable 50% advance deposit is required before architectural planning, design wireframing, or engineering begins.",
        "Final Balance Milestone: The remaining 50% balance is due upon final design approval and prior to live domain deployment or source file handover.",
        "Late Payment Policy: Invoices unpaid 14 calendar days past due date may incur a 1.5% monthly compound interest fee and temporary suspension of active services.",
        "Taxes & Transaction Fees: Prices are exclusive of applicable statutory taxes (such as GST or international processing fees) unless explicitly specified."
      ]
    },
    {
      id: "project-timeline",
      num: "05",
      icon: "schedule",
      title: "Project Timelines & Delivery",
      content: "Target milestone dates provided by TASK are estimated in good faith based on standard workflow cadence. Project timelines depend directly upon prompt receipt of client assets, content, design feedback, and approval sign-offs. Delays in client communication exceeding 5 business days will automatically extend delivery deadlines."
    },
    {
      id: "client-responsibilities",
      num: "06",
      icon: "assignment_ind",
      title: "Client Responsibilities & Assets",
      content: "The Client agrees to provide TASK with all necessary content, brand guidelines, high-resolution imagery, copy, and secure third-party login credentials essential for project execution. The Client warrants that all provided materials do not infringe upon any third-party intellectual property or privacy rights."
    },
    {
      id: "intellectual-property",
      num: "07",
      icon: "copyright",
      title: "Intellectual Property Rights",
      content: "Ownership rights are structured to protect both client deliverables and core agency framework code:",
      bullets: [
        "Client Ownership: Upon receipt of 100% full cleared payment, the Client receives full ownership rights to final approved visual designs, custom logos, and bespoke brand assets created for the project.",
        "Agency Retention: TASK retains full ownership of pre-existing software libraries, reusable components, development frameworks, and unselected draft concepts.",
        "Portfolio Showcase Right: TASK reserves the right to display completed project screenshots, visual mockups, and client testimonials in our agency portfolio unless restricted by a mutually executed Non-Disclosure Agreement (NDA)."
      ]
    },
    {
      id: "hosting-third-party",
      num: "08",
      icon: "dns",
      title: "Website Hosting & Third-Party Infrastructure",
      content: "TASK utilizes high-speed cloud infrastructure (such as Supabase, Vercel, or custom servers). However, domain registrars, third-party hosting, API services, payment gateways, and external plugins are subject to their respective third-party terms of service. TASK is not liable for service modifications or price adjustments enacted by third-party vendors."
    },
    {
      id: "limitation-liability",
      num: "09",
      icon: "shield_with_heart",
      title: "Limitation of Liability",
      content: "To the maximum extent permitted by applicable law, TASK, its directors, employees, or partners shall not be held liable for any indirect, incidental, consequential, or punitive damages, including loss of business profits, data corruption, or third-party server downtime arising from website usage."
    },
    {
      id: "cancellation-refund",
      num: "10",
      icon: "cancel",
      title: "Cancellation & Refund Policy",
      content: "Either party may terminate a project agreement upon written notice. If a project is cancelled by the Client prior to completion, TASK retains the 50% advance deposit to cover incurred labor and resource allocation. Completed milestone work and live-deployed digital assets are non-refundable."
    },
    {
      id: "privacy-policy-link",
      num: "11",
      icon: "policy",
      title: "Privacy & Data Protection",
      content: "Your use of TASK's digital services is also governed by our comprehensive Privacy Policy, which details our standards for data collection, storage, and 256-bit encryption protocols.",
      actionText: "Read Privacy Policy",
      actionTab: "privacy"
    },
    {
      id: "changes-to-terms",
      num: "12",
      icon: "published_with_changes",
      title: "Modifications to Terms",
      content: "TASK reserves the right to update or amend these Terms & Conditions at any time without prior individual notice. Revisions become effective immediately upon publication on this website. Continued use of our website or services constitutes acceptance of revised terms."
    },
    {
      id: "governing-law",
      num: "13",
      icon: "account_balance",
      title: "Governing Law & Jurisdiction",
      content: "These Terms & Conditions are governed by and construed in accordance with the laws of the operating jurisdiction of TASK Studio (West Bengal, India), without regard to its conflict of law principles. Any dispute arising under these terms shall be subject to exclusive jurisdiction of the competent courts in Kolkata, India."
    }
  ];

  return (
    <div className="relative min-h-screen bg-[#050505] text-on-surface selection:bg-primary selection:text-white">
      {/* Sticky Crimson Reading Progress Bar */}
      <div className="fixed top-0 left-0 right-0 z-50 h-1 bg-surface-container-high">
        <div 
          className="h-full bg-gradient-to-r from-primary via-secondary to-primary-container shadow-[0_0_12px_#E50914] transition-all duration-150 ease-out"
          style={{ width: `${scrollProgress}%` }}
        ></div>
      </div>

      {/* Dynamic Background Scene Layer */}
      <div className="fixed inset-0 w-full h-full pointer-events-none overflow-hidden z-0">
        <div className="absolute inset-0 bg-gradient-to-b from-[#050505]/90 via-[#050505]/80 to-[#050505] z-10"></div>
        <div className="absolute top-1/4 right-1/4 w-[700px] h-[500px] bg-primary-container/15 rounded-full blur-[140px] pointer-events-none z-10"></div>
        <img 
          alt="Light Background" 
          className="absolute inset-0 w-full h-full object-cover object-center opacity-85 pointer-events-none" 
          src={heroLightAsset} 
        />
        <img 
          alt="Dark Background" 
          className={`absolute inset-0 w-full h-full object-cover object-center blur-[6px] scale-105 transition-opacity duration-500 ease-in-out pointer-events-none ${
            activeDarkMode ? 'opacity-100' : 'opacity-0'
          }`} 
          src={heroDarkAsset} 
        />
      </div>

      <main className="relative z-20 pt-32 pb-section-gap px-container-padding-mobile md:px-container-padding-desktop max-w-5xl mx-auto">
        
        {/* Hero Section */}
        <section className="text-center mb-16 relative">
          {/* Animated Floating Legal Icon */}
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-gradient-to-br from-[#1c1b1b] to-[#0d0d0d] border border-primary/40 shadow-[0_0_30px_rgba(229,9,20,0.35)] mb-6 animate-float">
            <span className="material-symbols-outlined text-4xl text-primary drop-shadow-[0_0_12px_rgba(229,9,20,0.8)]">
              description
            </span>
          </div>

          <span className="font-label-caps text-label-caps text-secondary tracking-widest uppercase mb-4 block">
            AGENCY AGREEMENT
          </span>

          <h1 className="font-headline-xl text-4xl md:text-headline-xl text-on-surface mb-6 text-glow leading-tight">
            Terms & Conditions
          </h1>

          <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl mx-auto leading-relaxed">
            Please read these Terms & Conditions carefully before using TASK's website or purchasing any of our web design, branding, and management services.
          </p>

          <div className="mt-8 flex flex-wrap items-center justify-center gap-6 md:gap-8 text-xs font-label-caps text-on-surface-variant/70">
            <span className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-primary animate-pulse"></span>
              BINDING LEGAL CONTRACT
            </span>
            <span className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-primary animate-pulse"></span>
              EFFECTIVE IMMEDIATELY
            </span>
          </div>
        </section>

        {/* Quick Anchor Navigation Pill Bar */}
        <div className="hidden lg:flex items-center justify-center gap-2 overflow-x-auto py-4 px-6 rounded-full bg-[#121212]/80 backdrop-blur-md border border-secondary/20 mb-12 shadow-lg">
          {termsSections.map((sec) => (
            <a 
              key={sec.id}
              href={`#${sec.id}`}
              className="text-xs font-label-caps text-on-surface-variant hover:text-primary transition-colors px-3 py-1 rounded-full hover:bg-primary/10 whitespace-nowrap"
            >
              {sec.num}. {sec.title.split(' ')[0]}
            </a>
          ))}
        </div>

        {/* Terms Sections Stack */}
        <div className="space-y-8">
          {termsSections.map((sec) => (
            <div 
              key={sec.id}
              id={sec.id}
              className="solid-panel bg-[#121212]/90 backdrop-blur-md rounded-2xl p-6 md:p-10 border border-secondary/20 hover:border-primary/50 transition-all duration-300 shadow-[0_4px_24px_rgba(0,0,0,0.5)] hover:shadow-[0_4px_30px_rgba(229,9,20,0.15)] group relative"
            >
              {/* Elegant Section Number Badge */}
              <div className="absolute top-6 right-6 font-headline-lg text-3xl md:text-4xl text-primary/15 font-bold pointer-events-none group-hover:text-primary/30 transition-colors">
                {sec.num}
              </div>

              <div className="flex items-center gap-4 mb-4">
                <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/30 flex items-center justify-center text-primary group-hover:scale-110 transition-transform">
                  <span className="material-symbols-outlined text-xl">{sec.icon}</span>
                </div>
                <h2 className="font-headline-md text-xl md:text-2xl text-on-surface font-bold group-hover:text-primary transition-colors">
                  {sec.title}
                </h2>
              </div>

              <div className="w-full h-px bg-gradient-to-r from-primary/30 via-secondary/20 to-transparent mb-6"></div>

              <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed mb-4">
                {sec.content}
              </p>

              {sec.bullets && (
                <ul className="space-y-3 mt-4 font-body-md text-body-md text-on-surface/90">
                  {sec.bullets.map((bullet, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="material-symbols-outlined text-primary text-[18px] mt-1 shrink-0">check_circle</span>
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              )}

              {sec.note && (
                <div className="mt-4 p-4 rounded-xl bg-primary/5 border border-primary/20 text-xs text-primary-fixed-dim font-medium">
                  {sec.note}
                </div>
              )}

              {sec.actionTab && (
                <button
                  onClick={() => { setActiveTab(sec.actionTab); window.scrollTo({ top: 0, behavior: 'smooth' }); }}
                  className="mt-4 inline-flex items-center gap-2 text-secondary hover:text-white font-label-caps text-xs tracking-wider uppercase group-hover:translate-x-1 transition-all"
                >
                  {sec.actionText}
                  <span className="material-symbols-outlined text-sm">arrow_forward</span>
                </button>
              )}
            </div>
          ))}

          {/* Section 14: Highlighted Contact Information Card */}
          <div id="contact-info" className="solid-panel bg-gradient-to-br from-[#1c1b1b]/95 via-[#121212]/95 to-[#0a0a0a]/95 backdrop-blur-xl rounded-2xl p-8 md:p-12 border-2 border-primary/40 shadow-[0_0_35px_rgba(229,9,20,0.25)] relative overflow-hidden mt-12">
            <div className="absolute top-0 right-0 w-64 h-64 bg-primary-container/20 rounded-full blur-3xl pointer-events-none"></div>

            <div className="flex items-center gap-3 mb-6">
              <span className="material-symbols-outlined text-primary text-3xl">gavel</span>
              <div>
                <h3 className="font-headline-md text-2xl text-on-surface font-bold">14. Contact Information</h3>
                <p className="font-body-md text-sm text-on-surface-variant">Questions regarding these Terms & Conditions should be directed to our legal team.</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-white/10">
              <div className="space-y-4">
                <div>
                  <span className="font-label-caps text-xs text-secondary uppercase block mb-1">Company Name</span>
                  <span className="font-headline-md text-lg text-white font-bold">TASK Studio</span>
                </div>
                <div>
                  <span className="font-label-caps text-xs text-secondary uppercase block mb-1">Legal & Billing Email</span>
                  <a href="mailto:Taskfromindia@gmail.com" className="font-body-md text-on-surface hover:text-primary transition-colors font-medium">
                    Taskfromindia@gmail.com
                  </a>
                </div>
                <div>
                  <span className="font-label-caps text-xs text-secondary uppercase block mb-1">Direct Phone</span>
                  <a href="tel:+919310040848" className="font-body-md text-on-surface hover:text-primary transition-colors font-medium">
                    +91 93100 40848
                  </a>
                </div>
              </div>

              <div className="space-y-4">
                <div>
                  <span className="font-label-caps text-xs text-secondary uppercase block mb-1">Official Website</span>
                  <a href="https://task.com" target="_blank" rel="noopener noreferrer" className="font-body-md text-on-surface hover:text-primary transition-colors font-medium">
                    https://task.com
                  </a>
                </div>
                <div>
                  <span className="font-label-caps text-xs text-secondary uppercase block mb-1">Registered Address</span>
                  <span className="font-body-md text-on-surface font-medium block">
                    Kolkata, West Bengal, India
                  </span>
                </div>
                <div>
                  <span className="font-label-caps text-xs text-secondary uppercase block mb-1">Last Updated</span>
                  <span className="font-body-md text-white font-semibold">August 06, 2026</span>
                </div>
              </div>
            </div>

            <div className="mt-8 pt-6 border-t border-white/10 flex flex-wrap gap-4 items-center justify-between">
              <button 
                onClick={() => { setActiveTab('contact'); window.scrollTo({ top: 0, behavior: 'smooth' }); }}
                className="inline-flex items-center gap-2 bg-primary-container text-on-primary-container px-6 py-3 rounded-lg font-button-text text-xs hover:bg-primary-container/80 transition-all font-bold tracking-wider crimson-glow cursor-pointer"
              >
                Contact Agency Legal Team
                <span className="material-symbols-outlined text-sm">arrow_forward</span>
              </button>

              <button 
                onClick={() => { setActiveTab('privacy'); window.scrollTo({ top: 0, behavior: 'smooth' }); }}
                className="inline-flex items-center gap-2 bg-transparent border border-secondary/40 text-secondary px-6 py-3 rounded-lg font-button-text text-xs hover:bg-secondary/10 transition-all font-semibold tracking-wider cursor-pointer"
              >
                View Privacy Policy
              </button>
            </div>
          </div>

        </div>

      </main>

      {/* Floating Back to Top Button */}
      {showBackToTop && (
        <button
          onClick={scrollToTop}
          className="fixed bottom-8 right-8 z-50 w-12 h-12 rounded-full bg-primary-container text-on-primary-container border border-secondary/40 shadow-[0_0_20px_rgba(229,9,20,0.4)] flex items-center justify-center hover:scale-110 active:scale-95 transition-all crimson-glow cursor-pointer"
          title="Back to Top"
        >
          <span className="material-symbols-outlined text-2xl">arrow_upward</span>
        </button>
      )}
    </div>
  );
};

export default TermsPage;
